config/routes.rb
DevJobMappr::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks"}
  resources :jobs
  get "maps/index"
  get "maps/jobs_search" => 'maps#jobs_search', as: :map_jobs_search
  get "maps/experience_search" => 'maps#experience_search', as: :map_experience_search
  
  get "maps/indeed_search" => 'maps#indeed_search', as: :map_indeed_search

  root 'maps#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :job_title, :job_description, :experience_level, :job_type, :primary_languages, :job_link, :company_name, :company_address, :latitude, :longitude, presence: {message: "must be present"}

	# validates :latitude, :longitude, numericality: {message: 'must be a number'}

	geocoded_by :company_address
  before_validation :geocode 

  belongs_to :user

  scope :front_end, -> { where(job_type: 'Front-End')}
  scope :back_end, -> { where(job_type: 'Back-End')}
  scope :full_stack, -> { where(job_type: 'Full-Stack')}
  scope :junior, -> { where(experience_level: 'Junior')}
  scope :senior, -> { where(experience_level: 'Senior')}
  scope :internship, -> { where(experience_level: 'Internship')}

end

app/models/map.rb
class Map < ActiveRecord::Base
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :jobs

  def self.connect_to_linkedin(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.info.first_name,
	                          provider:auth.provider,
	                          uid:auth.uid,
	                          email:auth.info.email,
	                          password:Devise.friendly_token[0,20],
                          )
      end
    end
  end   

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_required
    if current_user.nil?
      redirect_to root_path
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if current_user
      @jobs = current_user.jobs
    else
      redirect_to new_user_session_path
      flash[:alert] = "Please sign in first"
    end
  end

  def create
    @job = Job.new(jobs_params)
    @job.user = current_user
    if @job.save
      flash[:notice] = "Your Job Has Been Posted Successfully"
      redirect_to jobs_path
    else 
      flash[:error] =  "Error In Your Submission"
      render action: 'new'
    end 
  end

  def new
    if current_user
      @job = Job.new 
    else
      redirect_to new_user_session_path
      flash[:alert] = "Please sign in first"
    end
  end

  def show
    if current_user
      @job = Job.find(params[:id])
    else
      redirect_to new_user_session_path
      flash[:alert] = "Please sign in first"
    end
  end

  def edit
    if current_user
      @job = Job.find(params[:id])
    else
      redirect_to new_user_session_path
      flash[:alert] = "Please sign in first"
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(jobs_params)
      flash[:notice] = "Successfully Updated Your Job"
      redirect_to jobs_path
    else
      render action 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "Successfully Deleted Your Job"
    redirect_to jobs_path
  end

  private
    def jobs_params
      params.require(:job).permit(:job_title, :job_description, :experience_level, :job_type, :primary_languages, :job_link, :company_name, :company_address, :latitude, :longitude)
    end 
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
    @maps = Map.all
    @jobs = Job.all
  end
    def jobs_search 
      if params[:category]==''
          @jobs = Job.all
      elsif params[:category]
         @jobs = Job.where(job_type: params[:category]) 
      end
        render json: @jobs
    end

    def experience_search
      if params[:category]==''
        @jobs = Job.all
      elsif params[:category]
        @jobs = Job.where(experience_level: params[:category])
      end
        render json: @jobs
    end

     def indeed_search
      if params[:category]==''
        @jobs = Job.all
      elsif params[:category]
        @jobs = Job.where(job_key: params[:category])
      end
        render json: @jobs
    end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	def linkedin
		auth = env["omniauth.auth"]
		@user = User.connect_to_linkedin(request.env["omniauth.auth"], current_user)

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
		else
			session["devise.linkedin_uid"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end

	def twitter
    auth = env["omniauth.auth"]
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_uid"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/jobs/_form.html.erb
<!-- JQuery for form tooltips -->
<script>
	$(function() {
	  $( document ).tooltip({
	    track: false
	  });
	});
</script>

<div id="job">
	<%= form_for @job do |f| %>
		<% if @job.errors.any? %>
			<div id="error_explanation">
			<h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

			<ul>
			<% @job.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
			</div>
		<% end %>

		<%= f.label :job_title %>
		<%= f.text_field :job_title, :required=>true, :title=>"Enter the position's job title" %>

		<%= f.label :job_description %>
		<%= f.text_area :job_description, :required=>true, :title=>"Enter a quick description of the position" %>

		<%= f.label :job_type %>
		<%= f.select :job_type, options_for_select(["Front-End", "Back-End", "Full-Stack"]), :title=>"Selct a job type"%>

		<%= f.label :experience_level %>
		<%= f.select :experience_level, options_for_select(["Senior", "Junior", "Internship"]), :title=>"Select experience level for this position" %>

		<%= f.label "Programming Language(s)" %>
		<%= f.text_field :primary_languages, :required=>true, :title=>"Enter primary language(s) required for this position" %>

		<%= f.label :job_link %>
		<%= f.text_field :job_link, :required=>true, :title=>"Enter a link to for candidate to apply at" %>

		<%= f.label :company_name %>
		<%= f.text_field :company_name, :required=>true, :title=>"Enter the name of your company" %>

		<%= f.label :company_address %>
		<%= f.text_field :company_address, :required=>true, :title=>"Enter your company's full address to be mapped properly" %>

		<%= f.hidden_field :latitude %>

		<%= f.hidden_field :longitude %>

		<%= f.submit :class=>"button tiny" %>
	<% end %>
</div>

app/views/jobs/edit.html.erb
<%= render partial: 'form' %>

app/views/jobs/index.html.erb
<h3 id="dash">Job Dashboard</h3>
<h5>You have a total of <%= current_user.jobs.length %> job(s) currently posted</h5>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<table>
  <thead>
    <tr>
      <th>Job Title</th>
      <th>Job Description</th>
      <th>Language(s)</th>
      <th>Job Type</th>
      <th>Experience</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  	<% current_user.jobs.each do |job|%>
	    <tr>
	      <td width="150"><%= job.job_title %></td>
	      <td width="400"><%= job.job_description %></td>
        <td width="170"><%= job.primary_languages %></td>
	      <td width="120"><%= job.job_type %></td>
	      <td width="120"><%= job.experience_level %></td>
	      <td width="100"><%= job.created_at.strftime("%m/%d/%Y") %></td>
	      <td width="50"><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' } %>/<%= link_to_modal "Edit", edit_job_path(job)%></td>
	    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to_modal 'Post a Job', new_job_path, :class=>"button tiny" %>
<br>
<%= link_to "Back to main", root_path %>
<br>

app/views/jobs/index.js.erb
  var geocoder;
  var map;
  var markers = [];


  function initialize() {
    geocoder = new google.maps.Geocoder();
    var myLatLng = new google.maps.LatLng(33.97545, -118.3473);

    var mapOptions = {
      zoom: 11,
      center: myLatLng,
      styles: stylesArray,
    }

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions); 

 }

  function indeedJobs2() {
    $.get("/jobs", {indeed_jobs: "indeed"}, null, 'script');
  }


  // function indeedJobs() {
  //   $.ajax ({
  //     type:"GET", 
  //     dataType: 'json',
  //     url: "http://api.indeed.com/ads/apisearch?publisher=9335086191163405&q=web+developer&l=santa+monica%2C+ca&v=2&format=json&latlong=1&st=employer&radius=25" 
  //     }).done(function(msg){
  //       console.log(msg)
  //       // mapIndeed(msg);
  //     });
  // }


  //this is a function mapMaker that takes the JSON and then plots the map. 
  function mapMaker(jobs_array){
     console.log(jobs_array);

    //for loop to place each marker with stored information. 
    var i, newMarker;
    var infowindow = new google.maps.InfoWindow();
    
    for (i=0; i < jobs_array.length; i++) {
      newMarker = new google.maps.Marker({
        position: new google.maps.LatLng(jobs_array[i].latitude, jobs_array[i].longitude),
        map: map, 
        title: (jobs_array[i].job_title),
        // animation: google.maps.Animation.DROP
        });
        google.maps.event.addListener(newMarker, 'click', (function(newMarker, i) {
          return function() {
            infowindow.setContent(jobs_array[i].job_title + "<br/>" + jobs_array[i].company_name + "<br/>" + jobs_array[i].primary_languages, + "<br/>"+jobs_array[i].experience_level);
            infowindow.open(map, newMarker);
          }
        })(newMarker, i));   
      //push items into an array
      markers.push(newMarker);    
    };



  function mapIndeed(jobs_array){
     console.log(jobs_array);

    //for loop to place each marker with stored information. 
    var i, newMarker;
    var infowindow = new google.maps.InfoWindow();
    
    for (i=0; i < jobs_array.length; i++) {
      newMarker = new google.maps.Marker({
        position: new google.maps.LatLng(jobs_array[i].results.latitude, jobs_array[i].results.longitude),
        map: map, 
        title: (jobs_array[i].results.jobtitle),
        // animation: google.maps.Animation.DROP
        });
        google.maps.event.addListener(newMarker, 'click', (function(newMarker, i) {
          return function() {
            infowindow.setContent(jobs_array[i].results.jobtitle + "<br/>" + jobs_array[i].results.company_name + "<br/>" + jobs_array[i].results.primary_languages, + "<br/>"+jobs_array[i].results.experience_level);
            infowindow.open(map, newMarker);
          }
        })(newMarker, i));   
      //push items into an array
      markers.push(newMarker);    
    };
 }
  //set map from array
  function setAllMap(map) {
    for (var i = 0; i < markers.length; i++) {
      markers[i].setMap(map);
    }
  }

  //clear the map
  function clearIt() {
    setAllMap(null);
    // markers = [];  
  }
google.maps.event.addDomListener(window, 'page:change', initialize);

app/views/jobs/new.html.erb
<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "DevJobs.Map" %></title>
    <link href='http://fonts.googleapis.com/css?family=Cambo' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="<%= root_path %>">DevJobs.<span id="title">Map</span></a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <%= link_to_modal 'Post a Job', new_job_path, :class=>"button tiny left job" %>
      <ul class="right">
        <li class="has-dropdown">
          <% if user_signed_in? %>
            <a href="<%= jobs_path %>", class="dashboard">Hello, <%= current_user.name == nil ? current_user.email : current_user.name%></a>
            <ul class="dropdown">
              <li> <%= link_to "Jobs Dashboard", jobs_path %> </li>
              <li> <%= link_to "Sign Out", destroy_user_session_path,:method => :delete %> </li>    
            </ul>
        </li>
        <% else %>
          <ul class="right">
            <li><%= link_to_modal "Sign In", new_user_session_path, :class=>"right" %></li>
            <li><%= link_to_modal "Sign Up", new_user_registration_path, :class=>"right" %></li>
          </ul>
        <% end %>
        </ul>
      </section>
    </nav>
    
    <%= javascript_include_tag "application" %>
    <%= yield %>
    
  </body>
</html>

app/views/maps/index.html.erb
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyAnC8QYcUdwqgPP-ukX0rPIu_KlyC1KE&libraries=visualization&sensor=true"></script>

<script type="text/javascript">
  var geocoder;
  var map;
  var markers = [];
  var heatmap;
  var stylesArray = [
    {
        "featureType": "water",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#a2daf2"
            }
        ]
    },
    {
        "featureType": "landscape.man_made",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#f7f1df"
            }
        ]
    },
    {
        "featureType": "landscape.natural",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#d0e3b4"
            }
        ]
    },
    {
        "featureType": "landscape.natural.terrain",
        "elementType": "geometry",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.park",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#bde6ab"
            }
        ]
    },
    {
        "featureType": "poi",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "poi.medical",
        "elementType": "geometry",
        "stylers": [
            {
                "color": "#fbd3da"
            }
        ]
    },
    {
        "featureType": "poi.business",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "on"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffe15f"
            }
        ]
    },
    {
        "featureType": "road.highway",
        "elementType": "geometry.stroke",
        "stylers": [
            {
                "color": "#efd151"
            }
        ]
    },
    {
        "featureType": "road.arterial",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "road.local",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "black"
            }
        ]
    },
    {
        "featureType": "transit.station.airport",
        "elementType": "geometry.fill",
        "stylers": [
            {
                "color": "#cfb2db"
            }
        ]
    }
  ]
             
  // var last_marker;
  function initialize() {
    geocoder = new google.maps.Geocoder();
    var myLatLng = new google.maps.LatLng(34.002197, -118.24176);

    var mapOptions = {
      zoom: 11,
      center: myLatLng,
      styles: stylesArray,
    }

    map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions); 
  
  var center;
    function calculateCenter() {
      center = map.getCenter();
    }
    google.maps.event.addDomListener(map, 'idle', function() {
      calculateCenter();
    });
    google.maps.event.addDomListener(window, 'resize', function() {
      map.setCenter(center);
    });
 }

 function loadData(jobs_array) {
    var heatMapData = [];
    var i, newMarker;
      for (i=0; i < jobs_array.length; i++) {
        heatMapData.push(new google.maps.LatLng(jobs_array[i].latitude, jobs_array[i].longitude));
      }
      var pointArray = new google.maps.MVCArray(heatMapData);
      heatmap = new google.maps.visualization.HeatmapLayer({
      data: pointArray,
      map: map
    });
      
  } 

 function toggleHeatmap() {
    isHeat = (heatmap.getMap() == null);
    heatmap.setMap(isHeat ? map : null);
    for(var i=0; i<markers.length; ++i)
      markers[i].setVisible(!isHeat);
  }

  // create a function that takes in argument 'x' from the click of the button and call is made through the GET and then after it gets a response it runs on mapMaker on line 71. 
  function searchMap(x) {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "<%= map_jobs_search_path %>?category="+x,
    }).done(function(msg){
      mapMaker(msg);
    });
  }

  function indeedJobs() {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "http://api.indeed.com/ads/apisearch?publisher=9335086191163405&q=web+developer&l=los+angeles%2C+ca&v=2&format=json&latlong=1&radius=25&limit=30&callback=?&fromage=30&highlight=0", 
      }).done(function(data){
        mapIndeed(data);
      });
      indeedJobs2();
    }

  function indeedJobs2() {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "http://api.indeed.com/ads/apisearch?publisher=9335086191163405&q=software+developer&l=los+angeles%2C+ca&v=2&format=json&latlong=1&radius=25&limit=30&callback=?&fromage=30&highlight=0", 
      }).done(function(data){
        mapIndeed(data);
      });
      indeedJobs3();
  }

  function indeedJobs3() {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "http://api.indeed.com/ads/apisearch?publisher=9335086191163405&q=developer&l=los+angeles%2C+ca&v=2&format=json&latlong=1&radius=25&limit=30&callback=?&fromage=30&highlight=0", 
      }).done(function(data){
        mapIndeed(data);
      });
      indeedJobs4();
  }

  function indeedJobs4() {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "http://api.indeed.com/ads/apisearch?publisher=9335086191163405&q=software-engineer&l=los+angeles%2C+ca&v=2&format=json&latlong=1&radius=25&limit=30&callback=?&fromage=30&highlight=0", 
      }).done(function(data){
        mapIndeed(data);
      });
  }

   function jobSearchMap(x) {
    $.ajax ({
      type:"GET", 
      dataType: "json",
      url: "<%= map_experience_search_path %>?category="+x,
    }).done(function(msg){
      mapMaker(msg);
    });
  }

  //this is a function mapMaker that takes the JSON and then plots the map. 
  function mapMaker(jobs_array){
    loadData (jobs_array);
    console.log(jobs_array);
    //for loop to place each marker with stored information. 
    var i, newMarker;
    var infowindow = new google.maps.InfoWindow();
    
    for (i=0; i < jobs_array.length; i++) {
      newMarker = new google.maps.Marker({
        position: new google.maps.LatLng(jobs_array[i].latitude, jobs_array[i].longitude),
        map: map, 
        title: (jobs_array[i].job_title),
        });
        google.maps.event.addListener(newMarker, 'click', (function(newMarker, i) {
          return function() {
            infowindow.setContent("<div id='embed'><strong> TITLE: </strong> " + jobs_array[i].job_title + "<br><br>" + 
              "<strong> COMPANY: </strong>" + jobs_array[i].company_name + "<br><br>" +  
              "<strong> DESCRIPTION: </strong>" + jobs_array[i].job_description + "<br><br>" +
              "<strong> LANGUAGE(S): </strong>" + jobs_array[i].primary_languages + "<br><br>" +
              '<a href="' + jobs_array[i].job_link + '" target="blank">Link to Job</a></div>');
            infowindow.open(map, newMarker);
          }
        })(newMarker, i));   
      //push items into an array
      markers.push(newMarker);    
    };
  }

  function mapIndeed(jobs_array){
    loadData (jobs_array);
    //for loop to place each marker with stored information. 
    var i, newMarker;
    var infowindow = new google.maps.InfoWindow();
    
    for (i=0; i < jobs_array["end"]-1; i++) {
      newMarker = new google.maps.Marker({
        position: new google.maps.LatLng(jobs_array["results"][i]["latitude"], jobs_array["results"][i]["longitude"]),
        map: map, 
        // icon: '<%= asset_path 'indeed.png' %>',
        title: (jobs_array["results"][i]["jobtitle"]),
        });
        // console.log(jobs_array["results"][i]["latitude"],jobs_array["results"][i]["longitude"] );
        google.maps.event.addListener(newMarker, 'click', (function(newMarker, i) {
          return function() {
            infowindow.setContent("<div id='embed'><strong> TITLE:</strong> " + jobs_array["results"][i]["jobtitle"] + "<br><br>" +
                                  "<strong> COMPANY:</strong> " + jobs_array["results"][i]["company"] + "<br><br>" + 
                                  "<strong> DESCRIPTION: </strong> " + jobs_array["results"][i]["snippet"] + "<br><br>" + 
                                  '<a href="' + jobs_array["results"][i]["url"] + '" target="blank">Link to Job</a></div>');
            infowindow.open(map, newMarker);
          }
        })(newMarker, i));   
      // push items into an array
      markers.push(newMarker);
    };
  }

  //set map from array
  function setAllMap(map) {
    for (var i = 0; i < markers.length; i++) {
      markers[i].setMap(map);
    }
  }

  //clear the map
  function clearIt() {
    setAllMap(null);
    // markers = [];  
  }

google.maps.event.addDomListener(window, 'page:change', initialize);
</script>

<script>
  $(function() {
    $( "#accordion" ).accordion({
      collapsible: true,
      active: false,
      heightStyle: "fill"
    });
  }); 
</script>

<div id="page-wrapper">
  <div id="map-wrapper">
   <div id="map-canvas"> </div>
   <div id= "sidebar">
    <div id="accordion">
      <h3><a href="#" onclick="searchMap('')">All Developer Jobs (<%= Job.count %>)</a></h3>
      <div>
        <% @jobs.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "searchMap('Front-End')">Front-End (<%= Job.front_end.count %>)</a></h3>
      <div>
        <% @jobs.front_end.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "searchMap('Back-End')">Back-End (<%= Job.back_end.count %>)</a></h3>
      <div>
        <% @jobs.back_end.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"><%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "searchMap('Full-Stack')">Full-Stack (<%= Job.full_stack.count %>)</a></h3>
      <div>
        <% @jobs.full_stack.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "jobSearchMap('Junior')">Junior Level (<%= Job.junior.count %>)</a></h3>
      <div>
        <% @jobs.junior.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "jobSearchMap('Senior')">Senior Level (<%= Job.senior.count %>)</a></h3>
      <div>
        <% @jobs.senior.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "jobSearchMap('Internship')">Internship (<%= Job.internship.count %>)</a></h3>
      <div>
        <% @jobs.internship.each do |job| %>
          <h6><a href="<%= job.job_link %>" target="blank"> <%= job.job_title %></a></h6>
        <% end %>
      </div>

      <h3><a href="#" onclick= "indeedJobs()">Indeed.com Jobs</a></h3>  
    </div>
    <div id="clear-btn">
      <button id="heat" class="button tiny" onclick="toggleHeatmap()"> Toggle HeatMap</button>
      <input type="button" class="button tiny" id="clear" onclick= "clearIt()" value="Clear Map" />
    </div>
    <p id="credits">Created at General Assembly LA by Daniel Iwao, Fernando Villasenor and Rachel Bailin.</p>
   </div>
  </div>
</div>